Update to cypress 3.1.5
Fixes error:
	Error: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'blob').

See https://github.com/cypress-io/cypress/issues/3008